export const ReduxActionKeys = {
  FCM: "FCM",
  AppVersion: 'APP_VERSION',
  CamerRoll: 'CAMERA_ROLL',
  Loading: 'LOADING',
  HasSession: 'HAS_SESSION',
  UserDetail: 'USER_DETAIL',
  OtherUserDetail: 'OTHER_USER_DETAIL',
  UserCredentials: 'USER_CREDENTIALS',
  RememberMe: 'REMEMBER_ME',
  Logout: 'LOGOUT',
  AppState: 'APP_STATE',
  NoInternet: 'NO_INTERNET',
  AllPosts: 'ALL_POSTS',
  UserPosts: 'USER_POSTS',
  UserFavorites: 'USER_FAVORITES',
  Post: 'POST',
  ActiveVideo: 'ACTIVE_VIDEO',
  Followers: 'FOLLOWERS',
  Following: 'FOLLOWING',
  ChatRoomId: 'CHAT_ROOM_ID',
  Rooms: 'ROOMS',
  GymRooms: 'GYM_ROOMS',
  UnRead: 'UNREAD',
  Stories: "STORIES",
  Comments: "COMMENTS",
  Media_Library: "MEDIA_LIBRARY",
  Selected_Media: "SELECTED_MEDIA",
  Searched_User: "SEARCHED_USER",
  Searched_Post: "SEARCHED_POST",
  Report_Modal: "REPORT_MODAL",
  WorkoutActive: 'WORKOUT_ACTIVE',
  WorkoutSheetRef: 'WORKOUT_SHEET_REF',
  WorkoutUpdated: 'WORKOUT_UPDATE',
  WorkoutExercises: 'WORKOUT_EXERCISES',
  AddSubChat: 'ADD_SUB_CHAT',
  RemoveSubChat: 'REMOVE_SUB_CHAT',
  UpdateSubChat: 'UPDATE_SUB_CHAT',
  WorkoutStartTime: 'WORKOUT_START_TIME',
  WorkoutElapsedTime: 'WORKOUT_ELAPSED_TIME',
  WorkoutTimerReset: 'WORKOUT_TIMER_RESET',
  UpdateWorkoutStats: 'UPDATE_WORKOUT_STATS'
}




